language: node_js

node_js:
  - '0.10'
  - '0.12'
  - '4.0'

before_install:
  - sudo apt-get install prosody
  - sudo service prosody stop
  - sudo cp test/resources/prosody.cfg.lua /etc/prosody/prosody.cfg.lua

before_script:
  - npm install -g grunt-cli

script:
  - npm run integration-test
