sudo: required

language: node_js

node_js:
  - '0.10'
  - '0.12'
  - '4.0'
  - '4.1'
  - '4.2'
  - '5.0'
  - 'stable'

before_install:
  - sudo apt-get install lua5.1 luarocks libexpat-dev libidn11-dev libssl-dev
  - sudo luarocks install luaexpat
  - sudo luarocks install luasocket
  - sudo luarocks install luafilesystem
  - mkdir prosody
  - hg clone https://hg.prosody.im/0.10 prosody-0.10
  - cd prosody-0.10
  - ./configure --with-lua-include=/usr/include/lua5.1 --prefix=$HOME/prosody
  - make
  - make install
  - cd $TRAVIS_BUILD_DIR
  - cp test/resources/prosody.cfg.lua ~/prosody/etc/prosody/prosody.cfg.lua

before_script: npm install -g grunt-cli

script: npm run full-test
